version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${PGDB}
      - POSTGRES_USER=${PGUSR}
      - POSTGRES_PASSWORD=${PGPWD}

  app:
    build: app
    restart: always
    depends_on:
      - db
    ports:
      - 5000:8000
    environment:
      - POSTGRES_DB=${PGDB}
      - POSTGRES_USER=${PGUSR}
      - POSTGRES_PASSWORD=${PGPWD}
      - DB_HOST=${DBHST}
      - DB_PORT=${DBPRT}
