version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${PGDB}
      - POSTGRES_USER=${PGUSR}
      - POSTGRES_PASSWORD=${PGPWD}}

  app:
    image: petterbejo/favorite-places-app
    restart: always
    ports:
      - 5000:8000
    environment:
      - POSTGRES_DB=${PGDB}
      - POSTGRES_USER=${PGUSR}
      - POSTGRES_PASSWORD=${PGPWD}}
